### ISSUE TITLE
为什么我选出来的速度全部都是0

### ISSUE THREAD

**Issue by tjyuli** [hello-earth/cloudflare-better-ip#16]
IP 地址           已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
116.214.62.53     4       4       0.00    81.44     0.00
116.214.34.66     4       4       0.00    85.58     0.00
116.214.34.9      4       4       0.00    85.58     0.00
64.110.91.92      4       4       0.00    91.13     0.00
193.123.224.240   4       4       0.00    93.67     0.00
193.123.245.252   4       4       0.00    93.99     0.00
193.123.224.89    4       4       0.00    95.55     0.00
64.110.88.30      4       4       0.00    96.11     0.00
64.110.82.162     4       4       0.00    98.51     0.00
64.110.65.45      4       4       0.00    99.50     0.00

**Comment by hello-earth** [comment]
你选的有问题，细节不讨论
