### ISSUE TITLE
Sharing method

### ISSUE THREAD

**Issue by EbadiDev** [hello-earth/cloudflare-better-ip#2]
Do you mind sharing your method ? In IRAN, we're facing some hard challenges for finding better IP and I tested all your IPs none of them was good to use for Iranian operators

**Comment by hello-earth** [comment]
my ips is only work good under the chinese internet situation, i can not make a detailed description, but you can see the repo which is modified by myself.
https://github.com/hello-earth/TXPortMap/blob/main/pkg/common/cdntest.go

**Comment by EbadiDev** [comment]
thanks i got it
