### ISSUE TITLE
三天打鱼两天晒网

### ISSUE THREAD

**Issue by DittCy** [hello-earth/cloudflare-better-ip#26]

**Comment by fulu568** [comment]
学会感恩，给你白嫖还挑肥拣瘦。别把自己变成精致的利己主义者。

**Comment by DittCy** [comment]
@fulu568 用你在这将大道理，你这种自以为是的恶心之人 比利己主义者强吗

**Comment by hello-earth** [comment]
这种引战的帖子就不要再发了，我尽量不再任何有倾向性的内容下留言，不想给任何人造成困扰。
