### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by guoyuan888** [hello-earth/cloudflare-better-ip#30]
亲爱的朋友。如果你决定放弃这个项目，可以私信分享一下吗？你的工作对我来说很重要，但现在已经二周没有更新了 非常感谢！

**Comment by hello-earth** [comment]
不是要放弃这个项目，只是这个项目最终的结果需要很多输入源配合才行，需要比较多的精力维护排除，最近有些忙所以没有顾上
