### ISSUE TITLE
更新

### ISSUE THREAD

**Issue by wsgehaishan520** [hello-earth/cloudflare-better-ip#4]
你会一直更新吗？如果没时间更新的话，可以把教程放在帖子下面吗？

**Comment by fulu568** [comment]
是啊，如果公开教程那绝对是福音啊

**Comment by hello-earth** [comment]
没意外会一直更新

**Comment by wsgehaishan520** [comment]
> 没意外会一直更新

good job

**Comment by wsgehaishan520** [comment]
我发现你能用的IP，IP打开后都有cloudflare或者cloudfront 字符特征。扫三字码IP的话用这个特征能确定吗

**Comment by hello-earth** [comment]
> 

基本可以，可以当作初筛的一步
